server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ems-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ems-app
          service: backend
          __path__: /var/log/mineenergy/*.log

  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          service: nginx
          __path__: /var/log/nginx/*.log

  - job_name: mosquitto
    static_configs:
      - targets:
          - localhost
        labels:
          job: mqtt
          service: mqtt
          __path__: /var/log/mosquitto/*.log
